### ISSUE TITLE
fix(collections): invalid array length 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#217]
## Description
I think somewhere in `collections` package some cases of array might have been missed. This is breaking the package.

```
Uncaught (in promise) RangeError: Invalid array length
    at EccUtilsDesignCollection._renderFooter (chunk.ZMHKGW67.js:118:10)
    at EccUtilsDesignCollection.render (chunk.ZMHKGW67.js:255:14)
    at EccUtilsDesignCollection.update (lit-element.js:115:28)
    at EccUtilsDesignCollection.performUpdate (reactive-element.js:816:22)
    at EccUtilsDesignCollection.scheduleUpdate (reactive-element.js:751:21)
    at EccUtilsDesignCollection.__enqueueUpdate (reactive-element.js:724:29)
_renderFooter @ chunk.ZMHKGW67.js:118
render @ chunk.ZMHKGW67.js:255
update @ lit-element.js:115
performUpdate @ reactive-element.js:816
scheduleUpdate @ reactive-element.js:751
__enqueueUpdate @ reactive-element.js:724
await in __enqueueUpdate (async)
requestUpdate @ reactive-element.js:699
set @ reactive-element.js:342
(anonymous) @ chunk.ZMHKGW67.js:144
handleEvent @ lit-html.js:1331
Show 7 more frames
Show less
```

**Comment by JaeAeich** [comment]
@git-anurag-hub I assume since I didn't set `totalItem` in `collections` that is why this issue was popping. If so I guess we can close this issue.
