### ISSUE TITLE
fix: dev build fails on file change 

### ISSUE THREAD

**Issue by JaeAeich** [elixir-cloud-aai/cloud-components#310]
## Description
The dev server break on file changes.

```
CLI Watching for changes in "."
CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
Cleaning up react source ...
CLI Change detected: change src/components/form/form.ts
ESM Build start
✘ [ERROR] Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/collection/index.ts"

✘ [ERROR] Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/code/index.ts"

✘ [ERROR] Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/details/index.ts"

✘ [ERROR] Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/form/index.ts"

✘ [ERROR] Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/index.ts"

ESM Build failed
Error: Build failed with 5 errors:
error: Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/collection/index.ts"
error: Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/code/index.ts"
error: Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/details/index.ts"
error: Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/form/index.ts"
error: Could not resolve "/home/jaeaeich/Desktop/cloud-components/packages/ecc-utils-design/src/react/index.ts"
    at failureErrorWithLog (/home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:1651:15)
    at /home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:1059:25
    at runOnEndCallbacks (/home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:1486:45)
    at buildResponseToResult (/home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:1057:7)
    at /home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:1086:16
    at responseCallbacks.<computed> (/home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:704:9)
    at handleIncomingPacket (/home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:764:9)
    at Socket.readFromStdout (/home/jaeaeich/Desktop/cloud-components/node_modules/tsup/node_modules/esbuild/lib/main.js:680:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
```

**Comment by anuragxxd** [comment]
Hey @JaeAeich, can you give more context over this like:
- Which package or application is the dev server running? Is it a specific package/app or a more whole dev env.
- Can you clarify if the issue is with the `ecc-utils-design` files itself, or with another app/package that is using or importing from `ecc-utils-design`?

**Comment by anuragxxd** [comment]
@JaeAeich, was the design package running as dev server or as the build output?

**Comment by JaeAeich** [comment]
Dev of design wasn't ran just the dev of Wes
